arch:
  - arm64

env:
  - DC_REPOSITORY=registry.vps2.izac.pro
  - IMAGE_NAME=node-test

services: docker

before install:
  - docker image build -t ${IMAGE_NAME} node/

script:
  - echo "it works"

after_success:
  - docker login https://${DC_REPOSITORY} -u ${DC_USERNAME} -p ${DC_PASS}
  - docker tag ${IMAGE_NAME} ${DC_REPOSITORY}/${IMAGE_NAME}:latest
  - docker push ${DC_REPOSITORY}/${IMAGE_NAME}
